### PR TITLE
changed regex for revision and graph

### PR DESCRIPTION
**Pull request by markusgraube**

### CODE REVIEW

**Comment by markusgraube** [comment]
@Tyr3al Can you check why the tests on travis are failing?

**Comment by Tyr3al** [comment]
@markusgraube will try.

**Comment by Tyr3al** [comment]
Fixed problem. I did not take into account that revisions identifiers could be longer than one character. 

Also added one simple selection test. `mvn test` passes now.

**Comment by markusgraube** [comment]
Looks good to me. Thank you!

**Pull request merged**
